//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechLineCaseAPI.MMThApi {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MMThApi.WS_InterfaceCRMSoap")]
    public interface WS_InterfaceCRMSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSCheckHistoryRO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TechLineCaseAPI.MMThApi.WSCheckHistoryROResponse WSCheckHistoryRO(TechLineCaseAPI.MMThApi.WSCheckHistoryRORequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/WSCheckHistoryRO", ReplyAction="*")]
        System.IAsyncResult BeginWSCheckHistoryRO(TechLineCaseAPI.MMThApi.WSCheckHistoryRORequest request, System.AsyncCallback callback, object asyncState);
        
        TechLineCaseAPI.MMThApi.WSCheckHistoryROResponse EndWSCheckHistoryRO(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSCheckHistoryRO", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WSCheckHistoryRORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CMPCDE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OFFCDE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string RONO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string REQUEST_NO;
        
        public WSCheckHistoryRORequest() {
        }
        
        public WSCheckHistoryRORequest(string CMPCDE, string OFFCDE, string RONO, string REQUEST_NO) {
            this.CMPCDE = CMPCDE;
            this.OFFCDE = OFFCDE;
            this.RONO = RONO;
            this.REQUEST_NO = REQUEST_NO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSCheckHistoryROResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WSCheckHistoryROResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable WSCheckHistoryROResult;
        
        public WSCheckHistoryROResponse() {
        }
        
        public WSCheckHistoryROResponse(System.Data.DataTable WSCheckHistoryROResult) {
            this.WSCheckHistoryROResult = WSCheckHistoryROResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_InterfaceCRMSoapChannel : TechLineCaseAPI.MMThApi.WS_InterfaceCRMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCheckHistoryROCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public WSCheckHistoryROCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TechLineCaseAPI.MMThApi.WSCheckHistoryROResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TechLineCaseAPI.MMThApi.WSCheckHistoryROResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_InterfaceCRMSoapClient : System.ServiceModel.ClientBase<TechLineCaseAPI.MMThApi.WS_InterfaceCRMSoap>, TechLineCaseAPI.MMThApi.WS_InterfaceCRMSoap {
        
        private BeginOperationDelegate onBeginWSCheckHistoryRODelegate;
        
        private EndOperationDelegate onEndWSCheckHistoryRODelegate;
        
        private System.Threading.SendOrPostCallback onWSCheckHistoryROCompletedDelegate;
        
        public WS_InterfaceCRMSoapClient() {
        }
        
        public WS_InterfaceCRMSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_InterfaceCRMSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_InterfaceCRMSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_InterfaceCRMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<WSCheckHistoryROCompletedEventArgs> WSCheckHistoryROCompleted;
        
        public TechLineCaseAPI.MMThApi.WSCheckHistoryROResponse WSCheckHistoryRO(TechLineCaseAPI.MMThApi.WSCheckHistoryRORequest request) {
            return base.Channel.WSCheckHistoryRO(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginWSCheckHistoryRO(TechLineCaseAPI.MMThApi.WSCheckHistoryRORequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginWSCheckHistoryRO(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TechLineCaseAPI.MMThApi.WSCheckHistoryROResponse EndWSCheckHistoryRO(System.IAsyncResult result) {
            return base.Channel.EndWSCheckHistoryRO(result);
        }
        
        private System.IAsyncResult OnBeginWSCheckHistoryRO(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TechLineCaseAPI.MMThApi.WSCheckHistoryRORequest request = ((TechLineCaseAPI.MMThApi.WSCheckHistoryRORequest)(inValues[0]));
            return this.BeginWSCheckHistoryRO(request, callback, asyncState);
        }
        
        private object[] OnEndWSCheckHistoryRO(System.IAsyncResult result) {
            TechLineCaseAPI.MMThApi.WSCheckHistoryROResponse retVal = this.EndWSCheckHistoryRO(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWSCheckHistoryROCompleted(object state) {
            if ((this.WSCheckHistoryROCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WSCheckHistoryROCompleted(this, new WSCheckHistoryROCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WSCheckHistoryROAsync(TechLineCaseAPI.MMThApi.WSCheckHistoryRORequest request) {
            this.WSCheckHistoryROAsync(request, null);
        }
        
        public void WSCheckHistoryROAsync(TechLineCaseAPI.MMThApi.WSCheckHistoryRORequest request, object userState) {
            if ((this.onBeginWSCheckHistoryRODelegate == null)) {
                this.onBeginWSCheckHistoryRODelegate = new BeginOperationDelegate(this.OnBeginWSCheckHistoryRO);
            }
            if ((this.onEndWSCheckHistoryRODelegate == null)) {
                this.onEndWSCheckHistoryRODelegate = new EndOperationDelegate(this.OnEndWSCheckHistoryRO);
            }
            if ((this.onWSCheckHistoryROCompletedDelegate == null)) {
                this.onWSCheckHistoryROCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWSCheckHistoryROCompleted);
            }
            base.InvokeAsync(this.onBeginWSCheckHistoryRODelegate, new object[] {
                        request}, this.onEndWSCheckHistoryRODelegate, this.onWSCheckHistoryROCompletedDelegate, userState);
        }
    }
}
